name: guidedlayout2_1748
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  intl: ^0.19.0
  image_picker: ^1.0.4
  pdf: ^3.11.1
  printing: ^5.12.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: 2.3.3
  flutter_riverpod: ^2.6.1
  fluttertoast: ^8.2.1

dev_dependencies:
  camera: ^0.10.5+2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobile_scanner: ^3.2.0
  path_provider: ^2.0.15
  # qr_flutter: ^4.1.0

  

flutter:
  uses-material-design: true
  assets:
    - assets/carousel1.jpg
    - assets/carousel2.jpg
    - assets/carousel3.jpg
    - assets/abs.jpg
    - assets/fullbody.jpg
    - assets/lowerbody.jpg
    - assets/benchpress.jpg
    - assets/abs1.jpg
    - assets/abs2.jpg
    - assets/abs3.jpg
    - assets/imagesGYM.png
    - assets/scanner.png
    - assets/abs.jpeg